---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-secret"
type: Opaque
stringData:
  DB: "mongodb://{{ .Values.secret.dbuser }}:{{ .Values.secret.dbpassword }}@{{ .Values.secret.dbhost }}:{{ .Values.secret.dbport }}/{{ .Values.secret.dbname }}"