apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: postgresql
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: {{ .Values.postgresql.image }}
        envFrom:
          - configMapRef:
              name: postgresql-confmap
          - secretRef:
              name: postgresql-secret
        ports:
        - containerPort: {{ .Values.postgresql.containerPort }}
        resources:
{{ toYaml .Values.postgresql.resources | indent 10 }}
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: {{ .Values.postgresql.containerPort }}
    targetPort: {{ .Values.postgresql.containerPort }}
  selector:
    app: postgresql
  clusterIP: None

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-confmap
data:
  POSTGRES_DB: "{{ .Values.postgresql.env.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.postgresql.env.POSTGRES_USER }}"
  PGDATA: "{{ .Values.postgresql.env.POSTGRES_DATA }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgresql.env.POSTGRES_PASSWORD }}"