---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-confmap"
data:
  postgres_user: {{ .Values.env.postgresUser }}
  report_path: {{ .Values.env.reportPath }}
  log_path: {{ .Values.env.logPath }}
  