---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-secret"
type: Opaque
stringData:
  postgres_password: "{{ .Values.env.postgresPassword }}"
  postgres_uri: "{{ .Values.env.postgresUri }}"