---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  updatePolicy:
{{ toYaml .Values.vpa.updatePolicy | indent 4 }} 
  resourcePolicy:
{{ toYaml .Values.vpa.resourcePolicy | indent 4 }} 